"""PDF medical report generation."""

from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Optional

from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from configs.constants import MODEL_VERSION
from reports.templates import ACCENT_COLOR, MARGIN, PAGE_SIZE, PRIMARY_COLOR, build_styles
from utils.paths import ensure_dir


def generate_pdf_report(
    output_path: str,
    patient_id: str,
    predictions: Dict[str, object],
    overlay_image_path: Optional[str] = None,
    model_version: str = MODEL_VERSION,
) -> str:
    """Generate a professional PDF report for one inference result.

    Args:
        output_path: Destination PDF file path.
        patient_id: Patient identifier displayed in the report.
        predictions: Structured prediction dictionary from post-processing.
        overlay_image_path: Optional Grad-CAM overlay image path.
        model_version: Trained model version string.

    Returns:
        Absolute path to the generated PDF file.
    """
    path = Path(output_path)
    ensure_dir(path.parent)
    styles = build_styles()
    doc = SimpleDocTemplate(
        str(path),
        pagesize=PAGE_SIZE,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=MARGIN,
        title="ChestVision AI Report",
    )

    story = []
    story.append(Paragraph("ChestVision AI — Chest X-ray Analysis Report", styles["title"]))
    story.append(
        Paragraph(
            "Automated multi-label thoracic disease screening (research use only)",
            styles["subtitle"],
        )
    )

    report_date = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    metadata_rows = [
        ["Patient ID", patient_id],
        ["Report Date", report_date],
        ["Model Version", model_version],
    ]
    metadata_table = Table(metadata_rows, colWidths=[5 * cm, 10 * cm])
    metadata_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), ACCENT_COLOR),
                ("TEXTCOLOR", (0, 0), (0, -1), PRIMARY_COLOR),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("GRID", (0, 0), (-1, -1), 0.5, PRIMARY_COLOR),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(metadata_table)
    story.append(Spacer(1, 0.4 * cm))

    story.append(Paragraph("Top Predictions", styles["section"]))
    top_rows = [["Disease", "Confidence"]]
    for item in predictions.get("top_predictions", []):
        top_rows.append([item["label"], f"{item['confidence_pct']}%"])
    top_table = Table(top_rows, colWidths=[8 * cm, 7 * cm])
    top_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), PRIMARY_COLOR),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, PRIMARY_COLOR),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [ACCENT_COLOR, None]),
            ]
        )
    )
    story.append(top_table)
    story.append(Spacer(1, 0.4 * cm))

    positive = predictions.get("positive_labels", [])
    story.append(Paragraph("Detected Conditions (above threshold)", styles["section"]))
    if positive:
        positive_rows = [["Disease", "Confidence"]]
        for item in positive:
            positive_rows.append([item["label"], f"{item['confidence_pct']}%"])
        positive_table = Table(positive_rows, colWidths=[8 * cm, 7 * cm])
        positive_table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 0.5, PRIMARY_COLOR),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                ]
            )
        )
        story.append(positive_table)
    else:
        story.append(Paragraph("No conditions exceeded the configured decision threshold.", styles["body"]))

    if overlay_image_path and Path(overlay_image_path).exists():
        story.append(Spacer(1, 0.4 * cm))
        story.append(Paragraph("Grad-CAM Explainability Overlay", styles["section"]))
        story.append(Image(overlay_image_path, width=14 * cm, height=10 * cm))

    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph("Clinical Disclaimer", styles["section"]))
    story.append(
        Paragraph(
            "This report is generated by an AI research system and is not intended for "
            "clinical diagnosis, treatment decisions, or emergency use. Results must be "
            "validated by a qualified radiologist or physician.",
            styles["disclaimer"],
        )
    )

    doc.build(story)
    return str(path.resolve())
